theme: jekyll-theme-cayman
title: Introduction to spatial analysis in R
tagline: Seminar on spatial analysis: 20-21 May 2019, Bilbao, Universidad del País Vasco.
description: Seminar on spatial analysis: 20-21 May 2019, Bilbao, Universidad del País Vasco.
